#!/bin/bash

#A script for running the "dedex" tool on a directory of dex files.
DIR="${1}"
RLPATH="$(realpath "$DIR")"
if [ "${RLPATH}" != "$(pwd)" ] ; then
  cd "$DIR"
fi


shopt -s nullglob
FILES=$()
read -r -a FILES <<< "$(echo *.dex)"
shopt -u nullglob

for d in "${FILES[@]}"
do
    OUT="./out"
    mkdir "${OUT}"

    apkds-dedexer -d "${OUT}" "./$d"

done
